# Hello Remote Sensing {.unnumbered}

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(fontawesome)
```

## Books

There are two main books used in this module.

-   Introductory Digital Image Processing: A Remote Sensing Perspective, Jensen (2015). Available as a physical copy or [online via the UCL library](https://read.kortext.com/reader/pdf/1872407/Cover)

-   [Earth Engine Fundamentals and Applications (author's live version)](https://docs.google.com/document/d/1dLSaGXlAnI0jK6LAB6F-gQLBA30NTT0pz1tovHfOmvI/edit) and [associated website](https://www.eefabook.org/go-to-the-book.html)

## Schedule

<table style="width:83%;">
<colgroup>
<col style="width: 16%" />
<col style="width: 16%" />
<col style="width: 16%" />
<col style="width: 16%" />
<col style="width: 16%" />
</colgroup>
<thead>
<tr class="header">
<th><p>Week</p></th>
<th style="text-align: left;"><p>Lecture</p></th>
<th style="text-align: center;"><p>Presentation</p></th>
<th><p>Practical</p></th>
<th style="text-align: center;"><p>Practical material</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p>1</p></td>
<td style="text-align: left;"><p>An Introduction to Remote Sensing</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023-lecture-1/#1"><code>r fa("person-chalkboard")</code></a></p></td>
<td><p>Getting started with remote sensing</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023/intro.html"><code>r fa("code")</code></a></p></td>
</tr>
<tr class="even">
<td><p>2</p></td>
<td style="text-align: left;"><p>Portfolio tools: Xaringan and Quarto</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023-lecture-2/#1"><code>r fa("person-chalkboard")</code></a></p></td>
<td><p>Portfolio</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023/2_portfolio.html"><code>r fa("code")</code></a></p></td>
</tr>
<tr class="odd">
<td><p>3</p></td>
<td style="text-align: left;"><p>Remote sensing data</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023-lecture-3/#1"><code>r fa("person-chalkboard")</code></a></p></td>
<td><p>Corrections</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023/3_corrections.html"><code>r fa("code")</code></a></p></td>
</tr>
<tr class="even">
<td><p>4</p></td>
<td style="text-align: left;"><p>Policy applications</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023-lecture-4/#1"><code>r fa("person-chalkboard")</code></a></p></td>
<td><p>Policy</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023/4_policy.html"><code>r fa("code")</code></a></p></td>
</tr>
<tr class="odd">
<td><p>5</p></td>
<td style="text-align: left;"><p>Google Earth Engine</p></td>
<td style="text-align: center;"></td>
<td><p>Google Earth Engine</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023/5_GEE_I.html"><code>r fa("code")</code></a></p></td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: left;"><p><strong>Reading week</strong></p></td>
<td style="text-align: center;"></td>
<td></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td><p>6</p></td>
<td style="text-align: left;"><p>Classification</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023-lecture-5/#1"><code>r fa("person-chalkboard")</code></a></p></td>
<td><p>Classification I</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023/6_classification_I.html"><code>r fa("code")</code></a></p></td>
</tr>
<tr class="even">
<td><p>7</p></td>
<td style="text-align: left;"><p>Classification the big questions (lecture 5 continued) and accuracy</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023-lecture-6/#1"><code>r fa("person-chalkboard")</code></a></p></td>
<td><p>Classification II</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023/7_classification_II.html"><code>r fa("code")</code></a></p></td>
</tr>
<tr class="odd">
<td><p>8</p></td>
<td style="text-align: left;"><p>Temperature and policy</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023-lecture-7/#1"><code>r fa("person-chalkboard")</code></a></p></td>
<td><p>Tempearture</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023/8_temperature.html"><code>r fa("code")</code></a></p></td>
</tr>
<tr class="even">
<td><p>9</p></td>
<td style="text-align: left;"><p>SAR</p></td>
<td style="text-align: center;"><p><a href="https://andrewmaclachlan.github.io/CASA0023-lecture-9/#1"><code>r fa("person-chalkboard")</code></a></p></td>
<td><p>SAR in GEE</p></td>
<td style="text-align: center;"><p><code>r fa("code")</code></p></td>
</tr>
<tr class="odd">
<td><p>10</p></td>
<td style="text-align: left;"><p>Learning diary Q and A</p></td>
<td style="text-align: center;"></td>
<td><p>Group presentations</p></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>

## Intended course learning outcomes

At the end of this module students will be able to:

-   Create a reproducible online portfolio workbook

-   Explain and evaluate common issues with urban and environmental policies at the local, national and international level that fail to consider spatial data

-   Revise vague and ambiguous development targets

-   Appropriately pre-process Earth observation imagery ready for analysis

-   Apply published methodologies to extract meaning from Earth observation data

-   Combine a variety of spatial data to demonstrate the benefits of data-informed governance and planning.

-   Create and design a reproducible workflow for consistent monitoring of urban and environmental metrics

-   Critique and optimise recently developed metropolitan climate mitigation strategies using appropriate spatial data, optimizing financial investment and environmental outcomes

## How to use this book

This website is hosted on GitHub and holds all the practical instructions and data. Data used within the practicals is available online, however occasionally websites can undergo maintenance or be inaccessible due to political factors such as government shutdowns.

To get the most out of this book spend a few minutes learning how to control it, in the top right of this webpage you will see the following tools:

-   `r fa("magnifying-glass")` search the entire book for a specific word

-   `r fa("bars")` control the side / menu bars

-   `r fa("toggle-off")` changes to light or dark mode

-   `r fa("github")` GitHub repository for this book

## Software installation

This course uses a range of software, some of which we have encountered before:

### SNAP

Sentinels Application Platform (SNAP) is open source software and has common tools and methods used on earth observation (EO) data. It's like QGIS for EO data, developed by the European Space Agency (ESA).

Download [the all toolboxes option for your operating system](https://step.esa.int/main/download/snap-download/)

### Google Earth Engine (GEE)

Google Earth Engine isn't software as such, but we will be using it within the module. You need:

-   A free Google account
-   To [sign up for GEE](https://earthengine.google.com/)

### R

You should have both R and RStudio installed from CASA0005

### QGIS

You should have QGIS installed from CASA0005
