# Corrections

### Review questions 




## Atmosphereic correction 

As described in the lecture, a rather simple method to correct raw satellite (or any other) imagery is called Dark Object Subtraction (DOS). This uses the logic that the darkest pixel within the image should be 0 and therefore any value that it has can be attributed to the atmosphere. 

So in order to remove the effect of the atmosphere we can the subtract the value from the rest of the pixels within the image. 

Here, we will need to download some raw satellite imagery, that is in Digital Number (DN). 

Then we will apply the formula to calculate the reluctance of the pixels by removing atmosphere effects.The formula for the cosine of the solar zenith angle correction (COST) is, this is the same as DOS but DOS omits `TAUz`

$$\rho_\lambda= \frac{(Lsat_{rad} - Lhaze1percent_{rad})\pi * d^2}{EO_{\lambda} * cos\theta S * TUAv + TAUz}$$

Where...

* $$\rho_\lambda$$ is the corrected value (DOS applied)

Top line of equation...

* $$Lsat_{rad}$$ =  at sensor radiance (recall DN goes to radiance)

* $$Lhaze1percent_{rad}$$ 




```{r}
# NOT RUN {
library(raster)
## Import meta-data and bands based on MTL file
mtlFile  <- system.file("external/landsat/LT52240631988227CUB02_MTL.txt", 
                                package="RStoolbox")
metaData <- readMeta(mtlFile)
# }
# NOT RUN {
lsat     <- stackMeta(mtlFile)
# }
# NOT RUN {
# }
# NOT RUN {
## Convert DN to top of atmosphere reflectance and brightness temperature
lsat_ref <- radCor(lsat, metaData = metaData, method = "apref")

## Correct DN to at-surface-reflecatance with DOS (Chavez decay model)
# }
# NOT RUN {
lsat_sref <- radCor(lsat, metaData = metaData, method = "dos")
# }
# NOT RUN {
## Correct DN to at-surface-reflecatance with simple DOS 
## Automatic haze estimation
hazeDN    <- estimateHaze(lsat, hazeBands = 1:4, darkProp = 0.01, plot = TRUE)
lsat_sref <- radCor(lsat, metaData = metaData, method = "sdos", 
                    hazeValues = hazeDN, hazeBands = 1:4)
# }
```



## Merging imagery 


## Enhancements

### Ratio

### Filtering

### PCA

### Texture



### Data fusion


