# Policy

## Resources

::: callout-tip
## This week

The focus this week is on identifying an earth observation dataset that could be used to assist a policy. 

The following papers will be useful:

-   Gerasopoulos, E., Bailey, J., Athanasopoulou, E., Speyer, O., Kocman, D., Raudner, A., Tsouni, A., Kontoes, H., Johansson, C., Georgiadis, C., Matthias, V., Kussul, N., Aquilino, M., Paasonen, P., 2022. [Earth observation: An integral part of a smart and sustainable city. Environmental Science & Policy 132, 296–307.](https://doi.org/10.1016/j.envsci.2022.02.033)

-   Kadhim, N., Mourshed, M., Bray, M., 2016. [Advances in remote sensing applications for urban sustainability. Euro-Mediterr J Environ Integr 1, 7.](https://doi.org/10.1007/s41207-016-0007-4)

-   Wellmann, T., Lausch, A., Andersson, E., Knapp, S., Cortinovis, C., Jache, J., Scheuer, S., Kremer, P., Mascarenhas, A., Kraemer, R., Haase, A., Schug, F., Haase, D., 2020. [Remote sensing in urban planning: Contributions towards ecologically sound policies? Landscape and Urban Planning 204, 103921.](https://doi.org/10.1016/j.landurbplan.2020.103921)

-   Searching for urban or city in the [International Journal of Applied Earth Observation and Geoinformation](https://www.sciencedirect.com/journal/international-journal-of-applied-earth-observation-and-geoinformation)

-   Jensen, J.R., 2015. [Introductory digital image processing: a remote sensing perspective.](https://read.kortext.com/reader/pdf/1872407/Cover) Prentice-Hall Inc.

    -   Urban-Suburban Phenological Cycles, Chapter 12, p.509

A very nice example that combines EO data and analysis we saw in CASA0005! The **spatial error model!**. We will discuss the specific data in future weeks.

-   Li, D., Newman, G.D., Wilson, B., Zhang, Y., Brown, R.D., 2022. [Modeling the relationships between historical redlining, urban heat, and heat-related emergency department visits: An examination of 11 Texas cities. Environment and Planning B: Urban Analytics and City Science 49, 933–952.](https://doi.org/10.1177/23998083211039854)

-   Martinez, A. de la I., Labib, S.M., 2023. [Demystifying normalized difference vegetation index (NDVI) for greenness exposure assessments and policy interventions in urban greening. Environmental Research 220, 115155.](https://doi.org/10.1016/j.envres.2022.115155)


:::


## Before the practical session

**For the practical session** this week **come prepared to talk** about the following:

- Explore the policies below

- Search for one metropolitan policy challenge (any city in the World) that could be solved by incorporating remotely sensed data

- Identify and evaluate a remotely sensed data set that could be used to assist with contributing to the policy goal

-  Demonstrate how this links to global agendas / goals

- Explain how it advances current local, national or global approaches.

Cities will have a diverse range of documentation available...

## Learning diary

**Following the practical and subsequent discussion** write up your case study city

The case study will be marked in the same manner set out in mark scheme for the learning diary. Specifically: 

* The summary criterion will refer to the summary of the policy and city you have selected.
* The application criterion will refer to how the remotely sensed data you sourced could be used to assist with contributing to the policy goal. How could the data be applied to solve the policy challenge. 
* The reflection criterion will refer to what you have learnt in relation to the policy, city and the application of the data. 

Should you struggle to find current approaches within your city explore other cities discussed within the practical. 

## Policies

A few examples to get you started ...you are **not** limited to this list. We explore some of these in more detail within future lectures. 

### Metropolitan 

* [Cape Town Municipal Spatial Development Framework](https://www.capetown.gov.za/work%20and%20business/planning-portal/regulations-and-legislations/cape-town-spatial-development-framework#section-docs)

* [Ahmedabad 2016 Heat Action Plan](https://www.nrdc.org/sites/default/files/ahmedabad-heat-action-plan-2016.pdf)

* [South Asia’s First Heat-Health Action Plan in Ahmedabad (Gujarat, India)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4024996/)

* [OneNYC 2050](https://onenyc.cityofnewyork.us/)

* [London Plan](https://www.london.gov.uk/what-we-do/planning/london-plan)

* [Perth and Peel @ 3.5 million](https://www.wa.gov.au/government/publications/perth-and-peel-35-million-frameworks)

### National

* [Singapore Master Plan](https://www.ura.gov.sg/Corporate/Planning/Master-Plan#:~:text=The%20Master%20Plan%20(MP)%20is,development%20of%20land%20and%20property.)

### International 

* [NEW!! World Cities Report 2022](https://unhabitat.org/sites/default/files/2022/06/wcr_2022.pdf)

* [C40 Cities](https://www.c40.org/)

* [United Nations New Urban Agenda](https://habitat3.org/the-new-urban-agenda/)

* [ARUP City Resilience Framework](https://www.arup.com/projects/city-resilience-index)

* [United Nations International Strategy for Disaster Reduction Sendai Framework](https://www.undrr.org/publication/sendai-framework-disaster-risk-reduction-2015-2030#:~:text=The%20Sendai%20Framework%20for%20Disaster,Investing%20in%20disaster%20reduction%20for)

* [Universal Sustainable Development Goals](https://www.undp.org/sustainable-development-goals#:~:text=The%20Sustainable%20Development%20Goals%20(SDGs)%2C%20also%20known%20as%20the,people%20enjoy%20peace%20and%20prosperity.) 
  * [The SDG targets](https://unstats.un.org/sdgs/metadata/?Text=&Goal=11&Target=)
  
* [Beat the Heat Handbook](https://www.unep.org/resources/report/beating-heat-sustainable-cooling-handbook-cities)  

## Example

For a written example read up to the study area section [in my paper on temperature mitigation (first 2 pages)](https://www.frontiersin.org/articles/10.3389/fbuil.2020.519599/full). Take note of table 1.

## Feedback 

Was anything that we explained unclear this week or was something really clear...let us know using the [feedback form](https://forms.gle/ArGHKA2sSmN29pVLA). It’s anonymous and we’ll use the responses to clear any issues up in the future / adapt the material.
