project:
  type: book
  output-dir: docs


book:
  title: "CASA0023 Remotely Sensing Cities and Environments"
  #author: Andy MacLachlan
  image: general_images/casa_logo.jpg
  #cover-image: general_images/casa_logo.jpg
  #date: r Sys.Date()
  #description: "The CASA0023 Remotely Sensing Cities and Environments practical book"
  navbar:
    logo: general_images/casa_logo.jpg
    collapse: true
    collapse-below: lg
    background: light
    #reader-mode: true
    search: true
    right:
      - icon: github
  sidebar:
    title: "CASA0023"
    style: floating
    reader-mode: true
  repo-url: https://github.com/andrewmaclachlan/CASA0023
  repo-actions: [edit, issue]

    #tools:
    #- icon: twitter
    #  href: https://twitter.com
    #- icon: github
    #  menu:
    #    - text: Source Code
    #      url:  https://code.com
    #    - text: Report a Bug
    #      url:  https://bugs.com
    #search: true
  #repo-url: https://github.com/jjallaire/hopr/
  #repo-actions: [edit]
  #sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - 2_portfolio.qmd
    - 3_corrections.qmd
    - 4_policy.qmd
    - 5_GEE_I.qmd
    - 6_classification_I.qmd
    - 7_classification_II.qmd
    - 8_temperature.qmd
    - resources.qmd
    - summary.qmd
    - references.qmd
  favicon: "assets/favicon.ico"	
  reader-mode: true


bibliography: references.bib

website:
  google-analytics: "UA-151934476-1"

format:
  html:
    theme: cosmo
    code-link: true

  pdf:
    documentclass: scrbook
#editor: visual

